# Generated by Django 3.2.22 on 2023-10-21 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20231007_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestbooking',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
