# Generated by Django 3.2.22 on 2023-10-26 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_guestbooking_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guestbooking',
            old_name='name',
            new_name='guest_name',
        ),
    ]
